name: Lint python
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        python-version: '3.12'
    - name: Install flake8
      run: python3 -m pip install flake8
    - name: Lint python
      run: flake8 .
    - uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "."
        jupyter: false
        version: "24.8.0"
