name: Run pytests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install graphviz graphviz-dev -y
        python3 -m pip install -r requirements.txt
    - name: Install pytest
      run: python3 -m pip install pytest
    - name: Run pytests
      run: timeout 300 python3 -m pytest